import { randomUUID } from 'node:crypto'
import { getPostgresPool } from '@/lib/postgres'
import { publishRunRequested, publishWorkspaceEventEnvelope } from '@/lib/redis-streams'
import {
  createGatewayAgent,
  deleteGatewayAgent,
  ensureGatewaySession,
  sendGatewayChatMessage,
  updateGatewayAgent,
} from '@/lib/gateway-client'
import { logger } from '@/lib/logger'
import { listAgents, listSessions } from '@/lib/openclaw'
import { emitWorkspaceEvent } from '@/lib/workspace-events'
import type {
  AuthMode,
  AuthenticatedUser,
  Department,
  TaskPriority,
  TaskStatus,
  WorkspaceAgent,
  WorkspaceEventEnvelope,
  WorkspaceMessage,
  WorkspaceRun,
  WorkspaceRunStatus,
  WorkspaceSnapshot,
  WorkspaceSummary,
  WorkspaceTaskEvent,
  WorkspaceTaskEventType,
  WorkspaceTask,
} from '@/lib/types'

const AMP_SCHEMA_VERSION = '2'
const LOCAL_OPERATOR_ID = 'local-operator'
const DEFAULT_WORKSPACE_NAME = 'agentStack Workspace'
const DEFAULT_PROJECT_NAME = 'Primary Project'
const DEFAULT_PROJECT_DESCRIPTION = 'Initial workspace generated by agentStack.'

declare global {
  // eslint-disable-next-line no-var
  var ampBootstrapPromise: Promise<void> | undefined
}

type UserRow = {
  id: string
  login: string
  name: string
  email: string | null
  avatar_url: string | null
  auth_mode: AuthMode
}

type WorkspaceRow = {
  id: string
  name: string
  goal: string | null
  created_at: string
  updated_at: string
}

type ProjectRow = {
  id: string
  workspace_id: string
  name: string
  description: string | null
  created_at: string
  updated_at: string
}

type AgentRow = {
  id: string
  workspace_id: string
  project_id: string
  openclaw_agent_id: string
  name: string
  role: string
  department: Department
  workspace_path: string
  is_core: boolean
  created_at: string
  updated_at: string
}

type TaskRow = {
  id: string
  workspace_id: string
  project_id: string
  title: string
  description: string | null
  status: TaskStatus
  priority: TaskPriority
  assigned_agent_id: string | null
  assigned_agent_name: string | null
  created_at: string
  updated_at: string
  completed_at: string | null
}

type MessageRow = {
  id: string
  workspace_id: string
  project_id: string
  agent_id: string
  session_key: string
  role: WorkspaceMessage['role']
  content: string
  created_at: string
}

type RunRow = {
  id: string
  workspace_id: string
  project_id: string
  agent_id: string
  session_key: string
  status: WorkspaceRunStatus
  prompt_excerpt: string | null
  response_excerpt: string | null
  error: string | null
  started_at: string
  finished_at: string | null
  updated_at: string
}

type TaskEventRow = {
  id: string
  workspace_id: string
  project_id: string
  task_id: string
  type: WorkspaceTaskEventType
  actor_user_id: string | null
  previous_status: TaskStatus | null
  next_status: TaskStatus | null
  previous_priority: TaskPriority | null
  next_priority: TaskPriority | null
  previous_assigned_agent_id: string | null
  next_assigned_agent_id: string | null
  created_at: string
}

type WorkspaceEventRow = {
  id: number
  workspace_id: string
  type: string
  entity_type: string
  entity_id: string | null
  payload: Record<string, unknown> | null
  created_at: string
}

type PlannerTask = {
  title: string
  description: string
  priority?: TaskPriority
  assignedDepartment?: Department
}

type TaskAuditEntry = {
  type: WorkspaceTaskEventType
  previousStatus: TaskStatus | null
  nextStatus: TaskStatus | null
  previousPriority: TaskPriority | null
  nextPriority: TaskPriority | null
  previousAssignedAgentId: string | null
  nextAssignedAgentId: string | null
}

const DEPARTMENT_CONFIG: Record<
  Department,
  {
    name: string
    role: string
    workspacePath: string
    isCore?: boolean
  }
> = {
  core: {
    name: 'Core Planner',
    role: 'Break goals into executable milestones, coordinate the team, and keep the workspace moving.',
    workspacePath: '/home/node/.openclaw/workspace/core',
    isCore: true,
  },
  research: {
    name: 'Research Lead',
    role: 'Research requirements, edge cases, references, and implementation constraints.',
    workspacePath: '/home/node/.openclaw/workspace/research',
  },
  builder: {
    name: 'Build Lead',
    role: 'Implement features, ship code, and keep product execution moving.',
    workspacePath: '/home/node/.openclaw/workspace/builder',
  },
  designer: {
    name: 'Design Lead',
    role: 'Shape interfaces, interaction models, and user-facing polish.',
    workspacePath: '/home/node/.openclaw/workspace/designer',
  },
  ops: {
    name: 'Ops Lead',
    role: 'Manage stack health, deployment posture, runtime concerns, and recoverability.',
    workspacePath: '/home/node/.openclaw/workspace/ops',
  },
  qa: {
    name: 'QA Lead',
    role: 'Validate workflows, catch regressions, and tighten release confidence.',
    workspacePath: '/home/node/.openclaw/workspace/qa',
  },
  marketing: {
    name: 'Marketing Lead',
    role: 'Frame the story, launch materials, and go-to-market surfaces.',
    workspacePath: '/home/node/.openclaw/workspace/marketing',
  },
}

function mapUser(row: UserRow): AuthenticatedUser {
  return {
    id: row.id,
    login: row.login,
    name: row.name,
    email: row.email,
    avatarUrl: row.avatar_url,
    authMode: row.auth_mode,
  }
}

function mapWorkspace(row: WorkspaceRow): WorkspaceSummary {
  return {
    id: row.id,
    name: row.name,
    goal: row.goal,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  }
}

function mapProject(row: ProjectRow) {
  return {
    id: row.id,
    workspaceId: row.workspace_id,
    name: row.name,
    description: row.description,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  }
}

function mapTask(row: TaskRow): WorkspaceTask {
  return {
    id: row.id,
    workspaceId: row.workspace_id,
    projectId: row.project_id,
    title: row.title,
    description: row.description,
    status: row.status,
    priority: row.priority,
    assignedAgentId: row.assigned_agent_id,
    assignedAgentName: row.assigned_agent_name,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    completedAt: row.completed_at,
  }
}

function mapMessage(row: MessageRow): WorkspaceMessage {
  return {
    id: row.id,
    workspaceId: row.workspace_id,
    projectId: row.project_id,
    agentId: row.agent_id,
    sessionKey: row.session_key,
    role: row.role,
    content: row.content,
    createdAt: row.created_at,
  }
}

function mapRun(row: RunRow): WorkspaceRun {
  return {
    id: row.id,
    workspaceId: row.workspace_id,
    projectId: row.project_id,
    agentId: row.agent_id,
    sessionKey: row.session_key,
    status: row.status,
    promptExcerpt: row.prompt_excerpt,
    responseExcerpt: row.response_excerpt,
    error: row.error,
    startedAt: row.started_at,
    finishedAt: row.finished_at,
    updatedAt: row.updated_at,
  }
}

function mapTaskEvent(row: TaskEventRow): WorkspaceTaskEvent {
  return {
    id: row.id,
    workspaceId: row.workspace_id,
    projectId: row.project_id,
    taskId: row.task_id,
    type: row.type,
    actorUserId: row.actor_user_id,
    previousStatus: row.previous_status,
    nextStatus: row.next_status,
    previousPriority: row.previous_priority,
    nextPriority: row.next_priority,
    previousAssignedAgentId: row.previous_assigned_agent_id,
    nextAssignedAgentId: row.next_assigned_agent_id,
    createdAt: row.created_at,
  }
}

function mapWorkspaceEvent(row: WorkspaceEventRow): WorkspaceEventEnvelope {
  return {
    id: row.id,
    workspaceId: row.workspace_id,
    type: row.type,
    entityType: row.entity_type,
    entityId: row.entity_id,
    payload: row.payload,
    createdAt: row.created_at,
  }
}

function normalizeDepartments(departments: unknown[]) {
  const requested = Array.isArray(departments) ? departments : []

  return Array.from(
    new Set(
      requested.filter((value): value is Department => (
        typeof value === 'string'
        && value in DEPARTMENT_CONFIG
        && value !== 'core'
      )),
    ),
  )
}

function normalizeTaskStatus(value: unknown): TaskStatus {
  if (value === 'in_progress' || value === 'blocked' || value === 'done') {
    return value
  }

  return 'backlog'
}

function normalizeTaskPriority(value: unknown): TaskPriority {
  if (value === 'low' || value === 'high') {
    return value
  }

  return 'medium'
}

function trimExcerpt(value: string, maxLength = 280) {
  const compact = value.replace(/\s+/g, ' ').trim()

  if (compact.length <= maxLength) {
    return compact || null
  }

  return `${compact.slice(0, maxLength - 1).trimEnd()}…`
}

function getCanonicalSessionKey(agentId: string) {
  return `agent:${agentId}:main`
}

function buildTaskAuditEntries(input: {
  previousStatus: TaskStatus
  nextStatus: TaskStatus
  previousPriority: TaskPriority
  nextPriority: TaskPriority
  previousAssignedAgentId: string | null
  nextAssignedAgentId: string | null
}) {
  const entries: TaskAuditEntry[] = []

  if (input.previousStatus !== input.nextStatus) {
    entries.push({
      type: 'status_changed',
      previousStatus: input.previousStatus,
      nextStatus: input.nextStatus,
      previousPriority: null,
      nextPriority: null,
      previousAssignedAgentId: null,
      nextAssignedAgentId: null,
    })
  }

  if (input.previousPriority !== input.nextPriority) {
    entries.push({
      type: 'priority_changed',
      previousStatus: null,
      nextStatus: null,
      previousPriority: input.previousPriority,
      nextPriority: input.nextPriority,
      previousAssignedAgentId: null,
      nextAssignedAgentId: null,
    })
  }

  if ((input.previousAssignedAgentId ?? null) !== (input.nextAssignedAgentId ?? null)) {
    entries.push({
      type: 'assignment_changed',
      previousStatus: null,
      nextStatus: null,
      previousPriority: null,
      nextPriority: null,
      previousAssignedAgentId: input.previousAssignedAgentId ?? null,
      nextAssignedAgentId: input.nextAssignedAgentId ?? null,
    })
  }

  return entries
}

function extractTextFromUnknown(value: unknown): string {
  if (typeof value === 'string') {
    return value.trim()
  }

  if (Array.isArray(value)) {
    return value
      .map((entry) => extractTextFromUnknown(entry))
      .filter(Boolean)
      .join('\n')
      .trim()
  }

  if (!value || typeof value !== 'object') {
    return ''
  }

  const record = value as Record<string, unknown>

  return [
    record.visibleText,
    record.text,
    record.content,
    record.message,
    record.body,
    record.output_text,
    record.outputText,
    record.parts,
    record.contentParts,
  ]
    .map((entry) => extractTextFromUnknown(entry))
    .find(Boolean) || ''
}

function extractRoleFromUnknown(value: unknown): WorkspaceMessage['role'] | null {
  if (!value || typeof value !== 'object') {
    return null
  }

  const record = value as Record<string, unknown>
  const rawRole = [record.role, record.kind, record.senderRole].find((entry) => typeof entry === 'string') as string | undefined

  if (rawRole === 'user' || rawRole === 'assistant' || rawRole === 'system') {
    return rawRole
  }

  return null
}

function extractPlannerPayload(reply: string) {
  const fencedMatch = reply.match(/```json\s*([\s\S]*?)```/i)
  const candidate = fencedMatch?.[1] || reply
  const start = candidate.indexOf('{')
  const end = candidate.lastIndexOf('}')

  if (start === -1 || end === -1 || end <= start) {
    return null
  }

  try {
    const parsed = JSON.parse(candidate.slice(start, end + 1)) as {
      projectSummary?: string
      tasks?: PlannerTask[]
    }

    if (!Array.isArray(parsed.tasks)) {
      return null
    }

    return {
      projectSummary: typeof parsed.projectSummary === 'string' ? parsed.projectSummary.trim() : '',
      tasks: parsed.tasks
        .filter((task) => task && typeof task.title === 'string' && task.title.trim() !== '')
        .slice(0, 8),
    }
  } catch {
    return null
  }
}

async function getUserById(userId: string) {
  await ensureAmpSchema()
  const pool = getPostgresPool()
  const result = await pool.query<UserRow>(
    `
      SELECT id, login, name, email, avatar_url, auth_mode
      FROM amp.users
      WHERE id = $1
    `,
    [userId],
  )

  return result.rows[0] ? mapUser(result.rows[0]) : null
}

async function getWorkspaceForUser(userId: string) {
  await ensureAmpSchema()
  const pool = getPostgresPool()
  const workspaceResult = await pool.query<WorkspaceRow>(
    `
      SELECT id, name, goal, created_at, updated_at
      FROM amp.workspaces
      WHERE owner_user_id = $1
      ORDER BY created_at ASC
      LIMIT 1
    `,
    [userId],
  )
  const workspace = workspaceResult.rows[0]

  if (!workspace) {
    return null
  }

  const projectResult = await pool.query<ProjectRow>(
    `
      SELECT id, workspace_id, name, description, created_at, updated_at
      FROM amp.projects
      WHERE workspace_id = $1
      ORDER BY created_at ASC
      LIMIT 1
    `,
    [workspace.id],
  )

  return {
    workspace: mapWorkspace(workspace),
    project: projectResult.rows[0] ? mapProject(projectResult.rows[0]) : null,
  }
}

async function listWorkspaceAgentRows(workspaceId: string) {
  const pool = getPostgresPool()
  const result = await pool.query<AgentRow>(
    `
      SELECT
        id,
        workspace_id,
        project_id,
        openclaw_agent_id,
        name,
        role,
        department,
        workspace_path,
        is_core,
        created_at,
        updated_at
      FROM amp.agents
      WHERE workspace_id = $1
      ORDER BY
        is_core DESC,
        created_at ASC
    `,
    [workspaceId],
  )

  return result.rows
}

async function listWorkspaceTaskRows(workspaceId: string) {
  const pool = getPostgresPool()
  const result = await pool.query<TaskRow>(
    `
      SELECT
        tasks.id,
        tasks.workspace_id,
        tasks.project_id,
        tasks.title,
        tasks.description,
        tasks.status,
        tasks.priority,
        tasks.assigned_agent_id,
        agents.name AS assigned_agent_name,
        tasks.created_at,
        tasks.updated_at,
        tasks.completed_at
      FROM amp.tasks AS tasks
      LEFT JOIN amp.agents AS agents
        ON agents.id = tasks.assigned_agent_id
      WHERE tasks.workspace_id = $1
      ORDER BY
        CASE tasks.priority
          WHEN 'high' THEN 0
          WHEN 'medium' THEN 1
          ELSE 2
        END,
        CASE tasks.status
          WHEN 'in_progress' THEN 0
          WHEN 'blocked' THEN 1
          WHEN 'backlog' THEN 2
          ELSE 3
        END,
        tasks.updated_at DESC
    `,
    [workspaceId],
  )

  return result.rows
}

async function listWorkspaceMessageRows(workspaceId: string, agentId?: string) {
  const pool = getPostgresPool()
  const result = await pool.query<MessageRow>(
    `
      SELECT
        id,
        workspace_id,
        project_id,
        agent_id,
        session_key,
        role,
        content,
        created_at
      FROM amp.messages
      WHERE workspace_id = $1
        AND ($2::text IS NULL OR agent_id = $2)
      ORDER BY created_at ASC
      LIMIT 200
    `,
    [workspaceId, agentId ?? null],
  )

  return result.rows
}

async function listWorkspaceRunRows(workspaceId: string, agentId?: string) {
  const pool = getPostgresPool()
  const result = await pool.query<RunRow>(
    `
      SELECT
        id,
        workspace_id,
        project_id,
        agent_id,
        session_key,
        status,
        prompt_excerpt,
        response_excerpt,
        error,
        started_at,
        finished_at,
        updated_at
      FROM amp.runs
      WHERE workspace_id = $1
        AND ($2::text IS NULL OR agent_id = $2)
      ORDER BY updated_at DESC
      LIMIT 50
    `,
    [workspaceId, agentId ?? null],
  )

  return result.rows
}

async function listWorkspaceTaskEventRows(workspaceId: string) {
  const pool = getPostgresPool()
  const result = await pool.query<TaskEventRow>(
    `
      SELECT
        id,
        workspace_id,
        project_id,
        task_id,
        type,
        actor_user_id,
        previous_status,
        next_status,
        previous_priority,
        next_priority,
        previous_assigned_agent_id,
        next_assigned_agent_id,
        created_at
      FROM amp.task_events
      WHERE workspace_id = $1
      ORDER BY created_at DESC
      LIMIT 40
    `,
    [workspaceId],
  )

  return result.rows
}

async function listWorkspaceEventRowsSince(workspaceId: string, afterId?: number) {
  const pool = getPostgresPool()
  const result = await pool.query<WorkspaceEventRow>(
    `
      SELECT
        id,
        workspace_id,
        type,
        entity_type,
        entity_id,
        payload,
        created_at
      FROM amp.workspace_events
      WHERE workspace_id = $1
        AND ($2::bigint IS NULL OR id > $2)
      ORDER BY id ASC
      LIMIT 100
    `,
    [workspaceId, afterId ?? null],
  )

  return result.rows
}

async function getWorkspaceScopedProject(workspaceId: string, projectId: string) {
  const pool = getPostgresPool()
  const result = await pool.query<ProjectRow>(
    `
      SELECT id, workspace_id, name, description, created_at, updated_at
      FROM amp.projects
      WHERE id = $1
        AND workspace_id = $2
      LIMIT 1
    `,
    [projectId, workspaceId],
  )

  return result.rows[0] ?? null
}

async function getWorkspaceScopedAgent(workspaceId: string, agentId: string) {
  const pool = getPostgresPool()
  const result = await pool.query<AgentRow>(
    `
      SELECT
        id,
        workspace_id,
        project_id,
        openclaw_agent_id,
        name,
        role,
        department,
        workspace_path,
        is_core,
        created_at,
        updated_at
      FROM amp.agents
      WHERE id = $1
        AND workspace_id = $2
      LIMIT 1
    `,
    [agentId, workspaceId],
  )

  return result.rows[0] ?? null
}

async function getWorkspaceScopedTask(workspaceId: string, taskId: string) {
  const pool = getPostgresPool()
  const result = await pool.query<TaskRow>(
    `
      SELECT
        tasks.id,
        tasks.workspace_id,
        tasks.project_id,
        tasks.title,
        tasks.description,
        tasks.status,
        tasks.priority,
        tasks.assigned_agent_id,
        agents.name AS assigned_agent_name,
        tasks.created_at,
        tasks.updated_at,
        tasks.completed_at
      FROM amp.tasks AS tasks
      LEFT JOIN amp.agents AS agents
        ON agents.id = tasks.assigned_agent_id
      WHERE tasks.id = $1
        AND tasks.workspace_id = $2
      LIMIT 1
    `,
    [taskId, workspaceId],
  )

  return result.rows[0] ?? null
}

function mergeLiveAgentState(agentRows: AgentRow[], liveAgents: Awaited<ReturnType<typeof listAgents>>, liveSessions: Awaited<ReturnType<typeof listSessions>>): WorkspaceAgent[] {
  const liveById = new Map(liveAgents.map((agent) => [agent.id, agent]))
  const sessionCountByAgent = liveSessions.reduce<Record<string, number>>((accumulator, session) => {
    accumulator[session.agentId] = (accumulator[session.agentId] || 0) + 1
    return accumulator
  }, {})

  return agentRows.map((row) => {
    const live = liveById.get(row.openclaw_agent_id)

    return {
      id: row.id,
      workspaceId: row.workspace_id,
      projectId: row.project_id,
      openclawAgentId: row.openclaw_agent_id,
      name: row.name,
      role: row.role,
      department: row.department,
      workspacePath: row.workspace_path,
      isCore: row.is_core,
      status: live?.status ?? 'configured',
      model: live?.model ?? null,
      sessions: sessionCountByAgent[row.openclaw_agent_id] || live?.sessions || 0,
      updatedAt: live?.updatedAt || row.updated_at,
    }
  })
}

async function recordWorkspaceEvent(input: {
  workspaceId: string
  type: string
  entityType: string
  entityId?: string | null
  payload?: Record<string, unknown> | null
}) {
  const pool = getPostgresPool()
  const result = await pool.query<WorkspaceEventRow>(
    `
      INSERT INTO amp.workspace_events (
        workspace_id,
        type,
        entity_type,
        entity_id,
        payload
      )
      VALUES ($1, $2, $3, $4, $5)
      RETURNING
        id,
        workspace_id,
        type,
        entity_type,
        entity_id,
        payload,
        created_at
    `,
    [
      input.workspaceId,
      input.type,
      input.entityType,
      input.entityId ?? null,
      input.payload ?? null,
    ],
  )

  const row = result.rows[0]

  if (!row) {
    return null
  }

  const event = mapWorkspaceEvent(row)
  emitWorkspaceEvent(event)
  void publishWorkspaceEventEnvelope(event).catch((error) => {
    logger.warn('Workspace event publish failed', {
      error: error instanceof Error ? error.message : String(error),
      workspaceId: input.workspaceId,
      type: input.type,
    })
  })
  return event
}

async function recordTaskAuditEntries(input: {
  workspaceId: string
  projectId: string
  taskId: string
  actorUserId: string | null
  entries: TaskAuditEntry[]
}) {
  if (input.entries.length === 0) {
    return
  }

  const pool = getPostgresPool()

  for (const entry of input.entries) {
    await pool.query(
      `
        INSERT INTO amp.task_events (
          id,
          workspace_id,
          project_id,
          task_id,
          type,
          actor_user_id,
          previous_status,
          next_status,
          previous_priority,
          next_priority,
          previous_assigned_agent_id,
          next_assigned_agent_id
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
      `,
      [
        randomUUID(),
        input.workspaceId,
        input.projectId,
        input.taskId,
        entry.type,
        input.actorUserId,
        entry.previousStatus,
        entry.nextStatus,
        entry.previousPriority,
        entry.nextPriority,
        entry.previousAssignedAgentId,
        entry.nextAssignedAgentId,
      ],
    )
  }
}

async function createPlannerTasks(input: {
  goal: string
  departments: Department[]
  coreAgentId: string
}) {
  const prompt = [
    'You are the core planner for agentStack, an AI Agent Management Platform.',
    'Generate a compact initial execution plan for the workspace.',
    'Return strict JSON only with this shape:',
    '{"projectSummary":"string","tasks":[{"title":"string","description":"string","priority":"low|medium|high","assignedDepartment":"research|builder|designer|ops|qa|marketing|core"}]}',
    'Keep tasks actionable and concise. Use at most 6 tasks.',
    `Goal: ${input.goal}`,
    `Departments: ${['core', ...input.departments].join(', ')}`,
  ].join('\n')

  try {
    const sessionKey = getCanonicalSessionKey(input.coreAgentId)
    const result = await sendGatewayChatMessage({
      sessionKey,
      agentId: input.coreAgentId,
      message: prompt,
      timeoutMs: 90_000,
    })
    const latestAssistant = [...result.history]
      .reverse()
      .find((entry) => extractRoleFromUnknown(entry) === 'assistant')
    const parsed = extractPlannerPayload(extractTextFromUnknown(latestAssistant))

    if (parsed && parsed.tasks.length > 0) {
      return parsed
    }
  } catch (error) {
    logger.warn('Planner bootstrap failed', {
      agentId: input.coreAgentId,
      error: error instanceof Error ? error.message : String(error),
    })
  }

  return {
    projectSummary: 'Initial agentStack workspace created from the setup wizard.',
    tasks: [
      {
        title: 'Refine the product goal',
        description: 'Turn the setup prompt into a clear implementation objective and user outcome.',
        priority: 'high' as const,
        assignedDepartment: 'core' as const,
      },
      {
        title: 'Research the problem space',
        description: 'Collect references, constraints, and likely implementation risks.',
        priority: 'medium' as const,
        assignedDepartment: 'research' as const,
      },
      {
        title: 'Build the first milestone',
        description: 'Translate the initial plan into the first shippable implementation slice.',
        priority: 'high' as const,
        assignedDepartment: 'builder' as const,
      },
    ],
  }
}

export async function ensureAmpSchema() {
  if (!global.ampBootstrapPromise) {
    global.ampBootstrapPromise = (async () => {
      const pool = getPostgresPool()

      await pool.query('CREATE SCHEMA IF NOT EXISTS amp')
      await pool.query(`
        CREATE TABLE IF NOT EXISTS amp.metadata (
          singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
          schema_version TEXT NOT NULL,
          last_booted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `)
      await pool.query(`
        CREATE TABLE IF NOT EXISTS amp.users (
          id TEXT PRIMARY KEY,
          github_id TEXT UNIQUE,
          login TEXT NOT NULL,
          name TEXT NOT NULL,
          email TEXT,
          avatar_url TEXT,
          auth_mode TEXT NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `)
      await pool.query(`
        CREATE TABLE IF NOT EXISTS amp.workspaces (
          id TEXT PRIMARY KEY,
          owner_user_id TEXT NOT NULL REFERENCES amp.users(id) ON DELETE CASCADE,
          name TEXT NOT NULL,
          goal TEXT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `)
      await pool.query(`
        CREATE UNIQUE INDEX IF NOT EXISTS amp_workspaces_owner_user_id_idx
          ON amp.workspaces (owner_user_id)
      `)
      await pool.query(`
        CREATE TABLE IF NOT EXISTS amp.projects (
          id TEXT PRIMARY KEY,
          workspace_id TEXT NOT NULL REFERENCES amp.workspaces(id) ON DELETE CASCADE,
          name TEXT NOT NULL,
          description TEXT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `)
      await pool.query(`
        CREATE TABLE IF NOT EXISTS amp.agents (
          id TEXT PRIMARY KEY,
          workspace_id TEXT NOT NULL REFERENCES amp.workspaces(id) ON DELETE CASCADE,
          project_id TEXT NOT NULL REFERENCES amp.projects(id) ON DELETE CASCADE,
          openclaw_agent_id TEXT NOT NULL,
          name TEXT NOT NULL,
          role TEXT NOT NULL,
          department TEXT NOT NULL,
          workspace_path TEXT NOT NULL,
          is_core BOOLEAN NOT NULL DEFAULT FALSE,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `)
      await pool.query(`
        DROP INDEX IF EXISTS amp_agents_workspace_department_idx
      `)
      await pool.query(`
        CREATE INDEX IF NOT EXISTS amp_agents_workspace_department_lookup_idx
          ON amp.agents (workspace_id, department)
      `)
      await pool.query(`
        CREATE UNIQUE INDEX IF NOT EXISTS amp_agents_single_core_idx
          ON amp.agents (workspace_id)
          WHERE is_core = TRUE
      `)
      await pool.query(`
        CREATE TABLE IF NOT EXISTS amp.tasks (
          id TEXT PRIMARY KEY,
          workspace_id TEXT NOT NULL REFERENCES amp.workspaces(id) ON DELETE CASCADE,
          project_id TEXT NOT NULL REFERENCES amp.projects(id) ON DELETE CASCADE,
          assigned_agent_id TEXT REFERENCES amp.agents(id) ON DELETE SET NULL,
          title TEXT NOT NULL,
          description TEXT,
          status TEXT NOT NULL DEFAULT 'backlog',
          priority TEXT NOT NULL DEFAULT 'medium',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          completed_at TIMESTAMPTZ
        )
      `)
      await pool.query(`
        CREATE INDEX IF NOT EXISTS amp_tasks_workspace_updated_at_idx
          ON amp.tasks (workspace_id, updated_at DESC)
      `)
      await pool.query(`
        CREATE TABLE IF NOT EXISTS amp.messages (
          id TEXT PRIMARY KEY,
          workspace_id TEXT NOT NULL REFERENCES amp.workspaces(id) ON DELETE CASCADE,
          project_id TEXT NOT NULL REFERENCES amp.projects(id) ON DELETE CASCADE,
          agent_id TEXT NOT NULL REFERENCES amp.agents(id) ON DELETE CASCADE,
          session_key TEXT NOT NULL,
          role TEXT NOT NULL,
          content TEXT NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `)
      await pool.query(`
        CREATE INDEX IF NOT EXISTS amp_messages_workspace_created_at_idx
          ON amp.messages (workspace_id, created_at DESC)
      `)
      await pool.query(`
        CREATE TABLE IF NOT EXISTS amp.task_dependencies (
          id TEXT PRIMARY KEY,
          task_id TEXT NOT NULL REFERENCES amp.tasks(id) ON DELETE CASCADE,
          depends_on_task_id TEXT NOT NULL REFERENCES amp.tasks(id) ON DELETE CASCADE
        )
      `)
      await pool.query(`
        CREATE TABLE IF NOT EXISTS amp.runs (
          id TEXT PRIMARY KEY,
          workspace_id TEXT NOT NULL REFERENCES amp.workspaces(id) ON DELETE CASCADE,
          project_id TEXT NOT NULL REFERENCES amp.projects(id) ON DELETE CASCADE,
          agent_id TEXT NOT NULL REFERENCES amp.agents(id) ON DELETE CASCADE,
          session_key TEXT NOT NULL,
          status TEXT NOT NULL,
          prompt_excerpt TEXT,
          response_excerpt TEXT,
          error TEXT,
          started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          finished_at TIMESTAMPTZ,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `)
      await pool.query(`
        CREATE INDEX IF NOT EXISTS amp_runs_workspace_updated_at_idx
          ON amp.runs (workspace_id, updated_at DESC)
      `)
      await pool.query(`
        CREATE TABLE IF NOT EXISTS amp.task_events (
          id TEXT PRIMARY KEY,
          workspace_id TEXT NOT NULL REFERENCES amp.workspaces(id) ON DELETE CASCADE,
          project_id TEXT NOT NULL REFERENCES amp.projects(id) ON DELETE CASCADE,
          task_id TEXT NOT NULL REFERENCES amp.tasks(id) ON DELETE CASCADE,
          type TEXT NOT NULL,
          actor_user_id TEXT REFERENCES amp.users(id) ON DELETE SET NULL,
          previous_status TEXT,
          next_status TEXT,
          previous_priority TEXT,
          next_priority TEXT,
          previous_assigned_agent_id TEXT REFERENCES amp.agents(id) ON DELETE SET NULL,
          next_assigned_agent_id TEXT REFERENCES amp.agents(id) ON DELETE SET NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `)
      await pool.query(`
        CREATE INDEX IF NOT EXISTS amp_task_events_workspace_created_at_idx
          ON amp.task_events (workspace_id, created_at DESC)
      `)
      await pool.query(`
        CREATE TABLE IF NOT EXISTS amp.workspace_events (
          id BIGSERIAL PRIMARY KEY,
          workspace_id TEXT NOT NULL REFERENCES amp.workspaces(id) ON DELETE CASCADE,
          type TEXT NOT NULL,
          entity_type TEXT NOT NULL,
          entity_id TEXT,
          payload JSONB,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `)
      await pool.query(`
        CREATE INDEX IF NOT EXISTS amp_workspace_events_workspace_id_idx
          ON amp.workspace_events (workspace_id, id DESC)
      `)
      await pool.query(`
        CREATE TABLE IF NOT EXISTS amp.preferences (
          singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
          appearance_preference TEXT NOT NULL DEFAULT 'system',
          density_preference TEXT NOT NULL DEFAULT 'comfortable',
          show_completed_tasks BOOLEAN NOT NULL DEFAULT FALSE,
          refresh_interval_seconds INTEGER NOT NULL DEFAULT 15,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `)
      await pool.query(`
        INSERT INTO amp.preferences (singleton)
        VALUES (TRUE)
        ON CONFLICT (singleton) DO NOTHING
      `)
      await pool.query(`
        CREATE TABLE IF NOT EXISTS amp.mc_tasks (
          id TEXT PRIMARY KEY,
          title TEXT NOT NULL,
          description TEXT,
          status TEXT NOT NULL DEFAULT 'backlog',
          priority TEXT NOT NULL DEFAULT 'medium',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          completed_at TIMESTAMPTZ
        )
      `)
      await pool.query(`
        CREATE INDEX IF NOT EXISTS amp_mc_tasks_updated_at_idx
          ON amp.mc_tasks (updated_at DESC)
      `)
      await pool.query(
        `
          INSERT INTO amp.metadata (singleton, schema_version, last_booted_at)
          VALUES (TRUE, $1, NOW())
          ON CONFLICT (singleton)
          DO UPDATE SET
            schema_version = EXCLUDED.schema_version,
            last_booted_at = EXCLUDED.last_booted_at
        `,
        [AMP_SCHEMA_VERSION],
      )
    })()
  }

  await global.ampBootstrapPromise
}

export async function ensureLocalOperatorUser() {
  await ensureAmpSchema()
  const pool = getPostgresPool()
  await pool.query(
    `
      INSERT INTO amp.users (
        id,
        login,
        name,
        email,
        avatar_url,
        auth_mode
      )
      VALUES ($1, 'local', 'Local Operator', NULL, NULL, 'local')
      ON CONFLICT (id)
      DO UPDATE SET
        login = EXCLUDED.login,
        name = EXCLUDED.name,
        auth_mode = EXCLUDED.auth_mode,
        updated_at = NOW()
    `,
    [LOCAL_OPERATOR_ID],
  )

  const user = await getUserById(LOCAL_OPERATOR_ID)

  if (!user) {
    throw new Error('Unable to create the local operator user')
  }

  return user
}

export async function upsertGitHubUser(input: {
  githubId: string
  login: string
  name: string
  email?: string | null
  avatarUrl?: string | null
}) {
  await ensureAmpSchema()
  const pool = getPostgresPool()
  const id = `github:${input.githubId}`

  await pool.query(
    `
      INSERT INTO amp.users (
        id,
        github_id,
        login,
        name,
        email,
        avatar_url,
        auth_mode
      )
      VALUES ($1, $2, $3, $4, $5, $6, 'github')
      ON CONFLICT (github_id)
      DO UPDATE SET
        login = EXCLUDED.login,
        name = EXCLUDED.name,
        email = EXCLUDED.email,
        avatar_url = EXCLUDED.avatar_url,
        auth_mode = EXCLUDED.auth_mode,
        updated_at = NOW()
    `,
    [id, input.githubId, input.login, input.name, input.email ?? null, input.avatarUrl ?? null],
  )

  const user = await getUserById(id)

  if (!user) {
    throw new Error('Unable to load the GitHub user after upsert')
  }

  return user
}

export async function ensureUserRecord(session: AuthenticatedUser) {
  return session.authMode === 'local' ? ensureLocalOperatorUser() : getUserById(session.id)
}

export async function getWorkspaceSnapshotForUser(session: AuthenticatedUser, options?: { agentId?: string }) {
  const user = session.authMode === 'local' ? await ensureLocalOperatorUser() : await getUserById(session.id)

  if (!user) {
    return {
      needsSetup: true,
      authMode: session.authMode,
      user: null,
      workspace: null,
      project: null,
      agents: [],
      tasks: [],
      messages: [],
      runs: [],
      taskEvents: [],
    } satisfies WorkspaceSnapshot
  }

  const workspaceContext = await getWorkspaceForUser(user.id)

  if (!workspaceContext || !workspaceContext.project) {
    return {
      needsSetup: true,
      authMode: user.authMode,
      user,
      workspace: null,
      project: null,
      agents: [],
      tasks: [],
      messages: [],
      runs: [],
      taskEvents: [],
    } satisfies WorkspaceSnapshot
  }

  const [agentRows, taskRows, messageRows, runRows, taskEventRows, liveAgents, liveSessions] = await Promise.all([
    listWorkspaceAgentRows(workspaceContext.workspace.id),
    listWorkspaceTaskRows(workspaceContext.workspace.id),
    listWorkspaceMessageRows(workspaceContext.workspace.id, options?.agentId),
    listWorkspaceRunRows(workspaceContext.workspace.id, options?.agentId),
    listWorkspaceTaskEventRows(workspaceContext.workspace.id),
    listAgents().catch(() => []),
    listSessions().catch(() => []),
  ])

  return {
    needsSetup: false,
    authMode: user.authMode,
    user,
    workspace: workspaceContext.workspace,
    project: workspaceContext.project,
    agents: mergeLiveAgentState(agentRows, liveAgents, liveSessions),
    tasks: taskRows.map(mapTask),
    messages: messageRows.map(mapMessage),
    runs: runRows.map(mapRun),
    taskEvents: taskEventRows.map(mapTaskEvent),
  } satisfies WorkspaceSnapshot
}

export async function bootstrapWorkspaceForUser(session: AuthenticatedUser, input: {
  goal: string
  departments: Department[]
}) {
  await ensureAmpSchema()
  const user = session.authMode === 'local' ? await ensureLocalOperatorUser() : await getUserById(session.id)

  if (!user) {
    throw new Error('User record is missing')
  }

  const existingWorkspace = await getWorkspaceForUser(user.id)

  if (existingWorkspace?.workspace && existingWorkspace.project) {
    return getWorkspaceSnapshotForUser(user)
  }

  const goal = input.goal.trim()

  if (!goal) {
    throw new Error('A workspace goal is required')
  }

  const workspaceId = randomUUID()
  const projectId = randomUUID()
  const requestedDepartments = normalizeDepartments(input.departments)
  const departments = ['core', ...requestedDepartments] as Department[]
  const pool = getPostgresPool()

  await pool.query('BEGIN')

  try {
    await pool.query(
      `
        INSERT INTO amp.workspaces (id, owner_user_id, name, goal)
        VALUES ($1, $2, $3, $4)
      `,
      [workspaceId, user.id, DEFAULT_WORKSPACE_NAME, goal],
    )
    await pool.query(
      `
        INSERT INTO amp.projects (id, workspace_id, name, description)
        VALUES ($1, $2, $3, $4)
      `,
      [projectId, workspaceId, DEFAULT_PROJECT_NAME, DEFAULT_PROJECT_DESCRIPTION],
    )
    await pool.query('COMMIT')
  } catch (error) {
    await pool.query('ROLLBACK')
    throw error
  }

  for (const department of departments) {
    const config = DEPARTMENT_CONFIG[department]
    let openclawAgentId: string = department

    try {
      const created = await createGatewayAgent({
        name: department,
        workspace: config.workspacePath,
      })

      if (created.agentId?.trim()) {
        openclawAgentId = created.agentId.trim()
      }
    } catch (error) {
      logger.warn('Gateway agent creation failed during workspace bootstrap', {
        department,
        error: error instanceof Error ? error.message : String(error),
      })
    }

    const agentId = randomUUID()

    await pool.query(
      `
        INSERT INTO amp.agents (
          id,
          workspace_id,
          project_id,
          openclaw_agent_id,
          name,
          role,
          department,
          workspace_path,
          is_core
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
      `,
      [
        agentId,
        workspaceId,
        projectId,
        openclawAgentId,
        config.name,
        config.role,
        department,
        config.workspacePath,
        Boolean(config.isCore),
      ],
    )

    await ensureGatewaySession(getCanonicalSessionKey(openclawAgentId), openclawAgentId, config.name).catch((error) => {
      logger.warn('Gateway session bootstrap failed during workspace bootstrap', {
        department,
        error: error instanceof Error ? error.message : String(error),
        agentId: openclawAgentId,
      })
    })
  }

  const createdAgents = await listWorkspaceAgentRows(workspaceId)
  const coreAgentRow = createdAgents.find((agent: AgentRow) => agent.department === 'core')

  if (!coreAgentRow) {
    throw new Error('Core planner agent was not created')
  }

  const planner = await createPlannerTasks({
    goal,
    departments: requestedDepartments,
    coreAgentId: coreAgentRow.openclaw_agent_id,
  })

  const agentByDepartment = new Map(createdAgents.map((agent: AgentRow) => [agent.department, agent] as const))

  for (const task of planner.tasks) {
    const assignedAgent = task.assignedDepartment ? agentByDepartment.get(task.assignedDepartment) : null

    await pool.query(
      `
        INSERT INTO amp.tasks (
          id,
          workspace_id,
          project_id,
          assigned_agent_id,
          title,
          description,
          status,
          priority
        )
        VALUES ($1, $2, $3, $4, $5, $6, 'backlog', $7)
      `,
      [
        randomUUID(),
        workspaceId,
        projectId,
        assignedAgent?.id ?? null,
        task.title.trim(),
        task.description?.trim() || null,
        normalizeTaskPriority(task.priority),
      ],
    )
  }

  if (planner.projectSummary.trim()) {
    await pool.query(
      `
        UPDATE amp.projects
        SET description = $2,
            updated_at = NOW()
        WHERE id = $1
      `,
      [projectId, planner.projectSummary.trim()],
    )
  }

  return getWorkspaceSnapshotForUser(user)
}

export async function createWorkspaceAgentForUser(session: AuthenticatedUser, input: {
  projectId: string
  department: Department
  name: string
  role: string
}) {
  const user = session.authMode === 'local' ? await ensureLocalOperatorUser() : await getUserById(session.id)

  if (!user) {
    throw new Error('User record is missing')
  }

  const workspaceContext = await getWorkspaceForUser(user.id)

  if (!workspaceContext?.workspace || !workspaceContext.project) {
    throw new Error('Workspace setup has not been completed yet')
  }

  const name = input.name.trim()
  const role = input.role.trim()

  if (!name) {
    throw new Error('Agent name is required')
  }

  if (!role) {
    throw new Error('Agent role is required')
  }

  if (input.department === 'core') {
    throw new Error('The core planner agent is created during setup and cannot be added manually')
  }

  if (!input.projectId.trim()) {
    throw new Error('Project id is required')
  }

  const project = await getWorkspaceScopedProject(workspaceContext.workspace.id, input.projectId.trim())

  if (!project) {
    throw new Error('Project not found in this workspace')
  }

  const department = input.department
  const requestedAgentId = `${department}-${randomUUID().slice(0, 8)}`
  let openclawAgentId = requestedAgentId
  let workspacePath = `/home/node/.openclaw/workspace/${openclawAgentId}`

  try {
    const created = await createGatewayAgent({
      name: openclawAgentId,
      workspace: workspacePath,
    })

    if (created.agentId?.trim()) {
      openclawAgentId = created.agentId.trim()
      workspacePath = `/home/node/.openclaw/workspace/${openclawAgentId}`
      logger.info('Gateway agent created', {
        requestedId: requestedAgentId,
        actualId: openclawAgentId,
      })
    }
  } catch (error) {
    logger.warn('Gateway agent creation failed', {
      error: error instanceof Error ? error.message : String(error),
      openclawAgentId,
    })
  }

  const pool = getPostgresPool()
  const agentId = randomUUID()
  await pool.query(
    `
      INSERT INTO amp.agents (
        id,
        workspace_id,
        project_id,
        openclaw_agent_id,
        name,
        role,
        department,
        workspace_path,
        is_core
      )
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, FALSE)
    `,
    [
      agentId,
      workspaceContext.workspace.id,
      project.id,
      openclawAgentId,
      name,
      role,
      department,
      workspacePath,
    ],
  )

  await ensureGatewaySession(getCanonicalSessionKey(openclawAgentId), openclawAgentId, name).catch((error) => {
    logger.warn('Gateway session bootstrap failed for created agent', {
      error: error instanceof Error ? error.message : String(error),
      agentId: openclawAgentId,
    })
  })

  await recordWorkspaceEvent({
    workspaceId: workspaceContext.workspace.id,
    type: 'agent.created',
    entityType: 'agent',
    entityId: agentId,
    payload: {
      agentId,
      openclawAgentId,
      department,
      name,
    },
  })

  return getWorkspaceSnapshotForUser(user)
}

export async function updateWorkspaceAgentForUser(session: AuthenticatedUser, input: {
  agentId: string
  name?: string
  role?: string
}) {
  const user = session.authMode === 'local' ? await ensureLocalOperatorUser() : await getUserById(session.id)

  if (!user) {
    throw new Error('User record is missing')
  }

  const workspaceContext = await getWorkspaceForUser(user.id)

  if (!workspaceContext?.workspace) {
    throw new Error('Workspace setup has not been completed yet')
  }

  const pool = getPostgresPool()
  const currentResult = await pool.query<AgentRow>(
    `
      SELECT
        id,
        workspace_id,
        project_id,
        openclaw_agent_id,
        name,
        role,
        department,
        workspace_path,
        is_core,
        created_at,
        updated_at
      FROM amp.agents
      WHERE id = $1
        AND workspace_id = $2
    `,
    [input.agentId, workspaceContext.workspace.id],
  )

  const current = currentResult.rows[0]

  if (!current) {
    throw new Error('Agent not found')
  }

  const nextName = input.name?.trim() || current.name
  const nextRole = input.role?.trim() || current.role

  await pool.query(
    `
      UPDATE amp.agents
      SET
        name = $2,
        role = $3,
        updated_at = NOW()
      WHERE id = $1
    `,
    [
      current.id,
      nextName,
      nextRole,
    ],
  )

  await updateGatewayAgent({
    agentId: current.openclaw_agent_id,
    name: nextName,
  }).catch((error) => {
    logger.warn('Gateway agent update failed', {
      error: error instanceof Error ? error.message : String(error),
      agentId: current.openclaw_agent_id,
    })
  })

  await recordWorkspaceEvent({
    workspaceId: workspaceContext.workspace.id,
    type: 'agent.updated',
    entityType: 'agent',
    entityId: current.id,
    payload: {
      agentId: current.id,
      openclawAgentId: current.openclaw_agent_id,
      name: nextName,
      role: nextRole,
    },
  })

  return getWorkspaceSnapshotForUser(user)
}

export async function deleteWorkspaceAgentForUser(session: AuthenticatedUser, agentId: string) {
  const user = session.authMode === 'local' ? await ensureLocalOperatorUser() : await getUserById(session.id)

  if (!user) {
    throw new Error('User record is missing')
  }

  const workspaceContext = await getWorkspaceForUser(user.id)

  if (!workspaceContext?.workspace) {
    throw new Error('Workspace setup has not been completed yet')
  }

  const pool = getPostgresPool()
  const currentResult = await pool.query<AgentRow>(
    `
      SELECT
        id,
        workspace_id,
        project_id,
        openclaw_agent_id,
        name,
        role,
        department,
        workspace_path,
        is_core,
        created_at,
        updated_at
      FROM amp.agents
      WHERE id = $1
        AND workspace_id = $2
    `,
    [agentId, workspaceContext.workspace.id],
  )

  const current = currentResult.rows[0]

  if (!current) {
    throw new Error('Agent not found')
  }

  if (current.is_core) {
    throw new Error('The core planner agent cannot be deleted')
  }

  await pool.query(
    `
      DELETE FROM amp.agents
      WHERE id = $1
    `,
    [agentId],
  )

  await deleteGatewayAgent({
    agentId: current.openclaw_agent_id,
    deleteFiles: false,
  }).catch((error) => {
    logger.warn('Gateway agent deletion failed', {
      error: error instanceof Error ? error.message : String(error),
      agentId: current.openclaw_agent_id,
    })
  })

  await recordWorkspaceEvent({
    workspaceId: workspaceContext.workspace.id,
    type: 'agent.deleted',
    entityType: 'agent',
    entityId: current.id,
    payload: {
      agentId: current.id,
      openclawAgentId: current.openclaw_agent_id,
      name: current.name,
      department: current.department,
    },
  })

  return getWorkspaceSnapshotForUser(user)
}

export async function createWorkspaceTaskForUser(session: AuthenticatedUser, input: {
  title: string
  description?: string | null
  priority?: TaskPriority
  assignedAgentId?: string | null
}) {
  const user = session.authMode === 'local' ? await ensureLocalOperatorUser() : await getUserById(session.id)

  if (!user) {
    throw new Error('User record is missing')
  }

  const workspaceContext = await getWorkspaceForUser(user.id)

  if (!workspaceContext?.workspace || !workspaceContext.project) {
    throw new Error('Workspace setup has not been completed yet')
  }

  const title = input.title.trim()

  if (!title) {
    throw new Error('Task title is required')
  }

  let assignedAgentId: string | null = input.assignedAgentId ?? null

  if (assignedAgentId) {
    const assignedAgent = await getWorkspaceScopedAgent(workspaceContext.workspace.id, assignedAgentId)

    if (!assignedAgent) {
      throw new Error('Assigned agent was not found in this workspace')
    }

    assignedAgentId = assignedAgent.id
  }

  const pool = getPostgresPool()
  const taskId = randomUUID()
  await pool.query(
    `
      INSERT INTO amp.tasks (
        id,
        workspace_id,
        project_id,
        assigned_agent_id,
        title,
        description,
        status,
        priority
      )
      VALUES ($1, $2, $3, $4, $5, $6, 'backlog', $7)
    `,
    [
      taskId,
      workspaceContext.workspace.id,
      workspaceContext.project.id,
      assignedAgentId,
      title,
      input.description?.trim() || null,
      normalizeTaskPriority(input.priority),
    ],
  )

  await recordTaskAuditEntries({
    workspaceId: workspaceContext.workspace.id,
    projectId: workspaceContext.project.id,
    taskId,
    actorUserId: user.id,
    entries: [
      {
        type: 'created',
        previousStatus: null,
        nextStatus: 'backlog',
        previousPriority: null,
        nextPriority: normalizeTaskPriority(input.priority),
        previousAssignedAgentId: null,
        nextAssignedAgentId: assignedAgentId,
      },
    ],
  })

  await recordWorkspaceEvent({
    workspaceId: workspaceContext.workspace.id,
    type: 'task.created',
    entityType: 'task',
    entityId: taskId,
    payload: {
      taskId,
      title,
      priority: normalizeTaskPriority(input.priority),
      assignedAgentId,
    },
  })

  return getWorkspaceSnapshotForUser(user)
}

export async function updateWorkspaceTaskForUser(session: AuthenticatedUser, input: {
  id: string
  status?: TaskStatus
  priority?: TaskPriority
  assignedAgentId?: string | null
}) {
  const user = session.authMode === 'local' ? await ensureLocalOperatorUser() : await getUserById(session.id)

  if (!user) {
    throw new Error('User record is missing')
  }

  const workspaceContext = await getWorkspaceForUser(user.id)

  if (!workspaceContext?.workspace) {
    throw new Error('Workspace setup has not been completed yet')
  }

  const current = await getWorkspaceScopedTask(workspaceContext.workspace.id, input.id)

  if (!current) {
    throw new Error('Task not found')
  }

  const nextStatus = normalizeTaskStatus(input.status ?? current.status)
  const nextPriority = normalizeTaskPriority(input.priority ?? current.priority)
  let nextAssignedAgentId = input.assignedAgentId ?? current.assigned_agent_id

  if (nextAssignedAgentId) {
    const assignedAgent = await getWorkspaceScopedAgent(workspaceContext.workspace.id, nextAssignedAgentId)

    if (!assignedAgent) {
      throw new Error('Assigned agent was not found in this workspace')
    }

    nextAssignedAgentId = assignedAgent.id
  }

  const auditEntries = buildTaskAuditEntries({
    previousStatus: current.status,
    nextStatus,
    previousPriority: current.priority,
    nextPriority,
    previousAssignedAgentId: current.assigned_agent_id,
    nextAssignedAgentId,
  })

  if (auditEntries.length === 0) {
    return getWorkspaceSnapshotForUser(user)
  }

  const pool = getPostgresPool()
  await pool.query(
    `
      UPDATE amp.tasks
      SET
        status = $2,
        priority = $3,
        assigned_agent_id = $4,
        updated_at = NOW(),
        completed_at = CASE
          WHEN $2 = 'done' THEN COALESCE(completed_at, NOW())
          ELSE NULL
        END
      WHERE id = $1
        AND workspace_id = $5
    `,
    [
      input.id,
      nextStatus,
      nextPriority,
      nextAssignedAgentId,
      workspaceContext.workspace.id,
    ],
  )

  await recordTaskAuditEntries({
    workspaceId: workspaceContext.workspace.id,
    projectId: current.project_id,
    taskId: current.id,
    actorUserId: user.id,
    entries: auditEntries,
  })

  await recordWorkspaceEvent({
    workspaceId: workspaceContext.workspace.id,
    type: 'task.updated',
    entityType: 'task',
    entityId: current.id,
    payload: {
      taskId: current.id,
      status: nextStatus,
      priority: nextPriority,
      assignedAgentId: nextAssignedAgentId,
      changed: auditEntries.map((entry) => entry.type),
    },
  })

  return getWorkspaceSnapshotForUser(user)
}

export async function listMessagesForAgentForUser(session: AuthenticatedUser, agentId: string) {
  const user = session.authMode === 'local' ? await ensureLocalOperatorUser() : await getUserById(session.id)

  if (!user) {
    throw new Error('User record is missing')
  }

  const workspaceContext = await getWorkspaceForUser(user.id)

  if (!workspaceContext?.workspace) {
    throw new Error('Workspace setup has not been completed yet')
  }

  const agent = await getWorkspaceScopedAgent(workspaceContext.workspace.id, agentId)

  if (!agent) {
    throw new Error('Agent not found')
  }

  const messages = await listWorkspaceMessageRows(workspaceContext.workspace.id, agentId)
  return messages.map(mapMessage)
}

export async function sendMessageToAgentForUser(session: AuthenticatedUser, input: {
  agentId: string
  content: string
}) {
  const user = session.authMode === 'local' ? await ensureLocalOperatorUser() : await getUserById(session.id)

  if (!user) {
    throw new Error('User record is missing')
  }

  const workspaceContext = await getWorkspaceForUser(user.id)

  if (!workspaceContext?.workspace || !workspaceContext.project) {
    throw new Error('Workspace setup has not been completed yet')
  }

  const pool = getPostgresPool()
  const agentResult = await pool.query<AgentRow>(
    `
      SELECT
        id,
        workspace_id,
        project_id,
        openclaw_agent_id,
        name,
        role,
        department,
        workspace_path,
        is_core,
        created_at,
        updated_at
      FROM amp.agents
      WHERE id = $1
        AND workspace_id = $2
    `,
    [input.agentId, workspaceContext.workspace.id],
  )

  const agent = agentResult.rows[0]

  if (!agent) {
    throw new Error('Agent not found')
  }

  const content = input.content.trim()

  if (!content) {
    throw new Error('Message content is required')
  }

  const sessionKey = getCanonicalSessionKey(agent.openclaw_agent_id)
  const userMessageId = randomUUID()
  const runId = randomUUID()

  await pool.query(
    `
      INSERT INTO amp.messages (
        id,
        workspace_id,
        project_id,
        agent_id,
        session_key,
        role,
        content
      )
      VALUES ($1, $2, $3, $4, $5, 'user', $6)
    `,
    [userMessageId, workspaceContext.workspace.id, workspaceContext.project.id, agent.id, sessionKey, content],
  )

  await pool.query(
    `
      INSERT INTO amp.runs (
        id,
        workspace_id,
        project_id,
        agent_id,
        session_key,
        status,
        prompt_excerpt
      )
      VALUES ($1, $2, $3, $4, $5, 'running', $6)
    `,
    [runId, workspaceContext.workspace.id, workspaceContext.project.id, agent.id, sessionKey, trimExcerpt(content)],
  )

  await recordWorkspaceEvent({
    workspaceId: workspaceContext.workspace.id,
    type: 'message.created',
    entityType: 'message',
    entityId: userMessageId,
    payload: {
      agentId: agent.id,
      role: 'user',
      sessionKey,
    },
  })
  await recordWorkspaceEvent({
    workspaceId: workspaceContext.workspace.id,
    type: 'run.updated',
    entityType: 'run',
    entityId: runId,
    payload: {
      runId,
      agentId: agent.id,
      status: 'running',
      sessionKey,
    },
  })
  void publishRunRequested({
    runId,
    workspaceId: workspaceContext.workspace.id,
    projectId: workspaceContext.project.id,
    agentId: agent.id,
    sessionKey,
  }).catch((error) => {
    logger.warn('Run queue publish failed', {
      error: error instanceof Error ? error.message : String(error),
      runId,
    })
  })

  try {
    const result = await sendGatewayChatMessage({
      sessionKey,
      agentId: agent.openclaw_agent_id,
      message: content,
      timeoutMs: 90_000,
    })

    const latestAssistant = [...result.history]
      .reverse()
      .find((entry) => extractRoleFromUnknown(entry) === 'assistant')
    const assistantContent = extractTextFromUnknown(latestAssistant) || 'The run completed, but no assistant reply text was captured.'
    const assistantMessageId = randomUUID()

    await pool.query(
      `
        INSERT INTO amp.messages (
          id,
          workspace_id,
          project_id,
          agent_id,
          session_key,
          role,
          content
        )
        VALUES ($1, $2, $3, $4, $5, 'assistant', $6)
      `,
      [assistantMessageId, workspaceContext.workspace.id, workspaceContext.project.id, agent.id, sessionKey, assistantContent],
    )
    await pool.query(
      `
        UPDATE amp.runs
        SET
          status = 'completed',
          response_excerpt = $2,
          finished_at = NOW(),
          updated_at = NOW()
        WHERE id = $1
      `,
      [runId, trimExcerpt(assistantContent)],
    )

    await recordWorkspaceEvent({
      workspaceId: workspaceContext.workspace.id,
      type: 'message.created',
      entityType: 'message',
      entityId: assistantMessageId,
      payload: {
        agentId: agent.id,
        role: 'assistant',
        sessionKey,
      },
    })
    await recordWorkspaceEvent({
      workspaceId: workspaceContext.workspace.id,
      type: 'run.updated',
      entityType: 'run',
      entityId: runId,
      payload: {
        runId,
        agentId: agent.id,
        status: 'completed',
        sessionKey,
      },
    })
  } catch (error) {
    const message = error instanceof Error ? error.message : 'The gateway request failed'

    await pool.query(
      `
        UPDATE amp.runs
        SET
          status = 'failed',
          error = $2,
          finished_at = NOW(),
          updated_at = NOW()
        WHERE id = $1
      `,
      [runId, message],
    )
    await recordWorkspaceEvent({
      workspaceId: workspaceContext.workspace.id,
      type: 'run.updated',
      entityType: 'run',
      entityId: runId,
      payload: {
        runId,
        agentId: agent.id,
        status: 'failed',
        error: message,
        sessionKey,
      },
    })

    throw error
  }

  return listMessagesForAgentForUser(user, agent.id)
}

export async function listWorkspaceEventsForUser(session: AuthenticatedUser, afterId?: number) {
  const user = session.authMode === 'local' ? await ensureLocalOperatorUser() : await getUserById(session.id)

  if (!user) {
    throw new Error('User record is missing')
  }

  const workspaceContext = await getWorkspaceForUser(user.id)

  if (!workspaceContext?.workspace) {
    return []
  }

  const rows = await listWorkspaceEventRowsSince(workspaceContext.workspace.id, afterId)
  return rows.map(mapWorkspaceEvent)
}

export const __testing = {
  buildTaskAuditEntries,
  extractPlannerPayload,
  getCanonicalSessionKey,
}
